local M = {}

M.emojis = {
  { char = "😀", name = "grinning face" },
  { char = "😃", name = "grinning face with big eyes" },
  { char = "😄", name = "grinning face with smiling eyes" },
  { char = "😁", name = "beaming face with smiling eyes" },
  { char = "😆", name = "grinning squinting face" },
  { char = "😅", name = "grinning face with sweat" },
  { char = "🤣", name = "rolling on the floor laughing" },
  { char = "😂", name = "face with tears of joy" },
  { char = "🙂", name = "slightly smiling face" },
  { char = "🙃", name = "upside-down face" },
  { char = "😉", name = "winking face" },
  { char = "😊", name = "smiling face with smiling eyes" },
  { char = "😇", name = "smiling face with halo" },
  { char = "🥰", name = "smiling face with hearts" },
  { char = "😍", name = "smiling face with heart-eyes" },
  { char = "🤩", name = "star-struck" },
  { char = "😘", name = "face blowing a kiss" },
  { char = "😗", name = "kissing face" },
  { char = "😚", name = "kissing face with closed eyes" },
  { char = "😙", name = "kissing face with smiling eyes" },
  { char = "😋", name = "face savoring food" },
  { char = "😛", name = "face with tongue" },
  { char = "😜", name = "winking face with tongue" },
  { char = "🤪", name = "zany face" },
  { char = "😝", name = "squinting face with tongue" },
  { char = "🤑", name = "money-mouth face" },
  { char = "🤗", name = "hugging face" },
  { char = "🤭", name = "face with hand over mouth" },
  { char = "🤫", name = "shushing face" },
  { char = "🤔", name = "thinking face" },
  { char = "🤐", name = "zipper-mouth face" },
  { char = "🤨", name = "face with raised eyebrow" },
  { char = "😐", name = "neutral face" },
  { char = "😑", name = "expressionless face" },
  { char = "😶", name = "face without mouth" },
  { char = "😏", name = "smirking face" },
  { char = "😒", name = "unamused face" },
  { char = "🙄", name = "face with rolling eyes" },
  { char = "😬", name = "grimacing face" },
  { char = "🤥", name = "lying face" },
  { char = "😌", name = "relieved face" },
  { char = "😔", name = "pensive face" },
  { char = "😪", name = "sleepy face" },
  { char = "🤤", name = "drooling face" },
  { char = "😴", name = "sleeping face" },
  { char = "😷", name = "face with medical mask" },
  { char = "🤒", name = "face with temperature" },
  { char = "🤕", name = "face with head-bandage" },
  { char = "🤢", name = "nauseated face" },
  { char = "🤮", name = "face vomiting" },
  { char = "🤧", name = "sneezing face" },
  { char = "🥵", name = "hot face" },
  { char = "🥶", name = "cold face" },
  { char = "🥴", name = "woozy face" },
  { char = "😵", name = "dizzy face" },
  { char = "🤯", name = "exploding head" },
  { char = "🤠", name = "cowboy hat face" },
  { char = "🥳", name = "partying face" },
  { char = "😎", name = "smiling face with sunglasses" },
  { char = "🤓", name = "nerd face" },
  { char = "🧐", name = "face with monocle" },
  { char = "😕", name = "confused face" },
  { char = "😟", name = "worried face" },
  { char = "🙁", name = "slightly frowning face" },
  { char = "☹️", name = "frowning face" },
  { char = "😮", name = "face with open mouth" },
  { char = "😯", name = "hushed face" },
  { char = "😲", name = "astonished face" },
  { char = "😳", name = "flushed face" },
  { char = "🥺", name = "pleading face" },
  { char = "😦", name = "frowning face with open mouth" },
  { char = "😧", name = "anguished face" },
  { char = "😨", name = "fearful face" },
  { char = "😰", name = "face with open mouth and cold sweat" },
  { char = "😥", name = "sad but relieved face" },
  { char = "😢", name = "crying face" },
  { char = "😭", name = "loudly crying face" },
  { char = "😱", name = "face screaming in fear" },
  { char = "😖", name = "confounded face" },
  { char = "😣", name = "persevering face" },
  { char = "😞", name = "disappointed face" },
  { char = "😓", name = "downcast face with sweat" },
  { char = "😩", name = "weary face" },
  { char = "😫", name = "tired face" },
  { char = "🥱", name = "yawning face" },
  { char = "😤", name = "face with steam from nose" },
  { char = "😡", name = "pouting face" },
  { char = "😠", name = "angry face" },
  { char = "🤬", name = "face with symbols on mouth" },
  { char = "😈", name = "smiling face with horns" },
  { char = "👿", name = "angry face with horns" },
  { char = "💀", name = "skull" },
  { char = "☠️", name = "skull and crossbones" },
  { char = "💩", name = "pile of poo" },
  { char = "🤡", name = "clown face" },
  { char = "👹", name = "ogre" },
  { char = "👺", name = "goblin" },
  { char = "👻", name = "ghost" },
  { char = "👽", name = "alien" },
  { char = "👾", name = "alien monster" },
  { char = "🤖", name = "robot" },
  { char = "😺", name = "grinning cat" },
  { char = "😸", name = "grinning cat with smiling eyes" },
  { char = "😻", name = "smiling cat with heart-eyes" },
  { char = "😼", name = "cat with wry smile" },
  { char = "😽", name = "kissing cat" },
  { char = "🙀", name = "weary cat" },
  { char = "😿", name = "crying cat" },
  { char = "😾", name = "pouting cat" },
  { char = "🙈", name = "see-no-evil monkey" },
  { char = "🙉", name = "hear-no-evil monkey" },
  { char = "🙊", name = "speak-no-evil monkey" },
  { char = "💋", name = "kiss mark" },
  { char = "💌", name = "love letter" },
  { char = "💘", name = "heart with arrow" },
  { char = "💝", name = "heart with ribbon" },
  { char = "💖", name = "sparkling heart" },
  { char = "💗", name = "growing heart" },
  { char = "💓", name = "beating heart" },
  { char = "💞", name = "revolving hearts" },
  { char = "💕", name = "two hearts" },
  { char = "💟", name = "heart decoration" },
  { char = "❣", name = "heart exclamation" },
  { char = "💔", name = "broken heart" },
  { char = "❤️", name = "red heart" },
  { char = "🧡", name = "orange heart" },
  { char = "💛", name = "yellow heart" },
  { char = "💚", name = "green heart" },
  { char = "💙", name = "blue heart" },
  { char = "💜", name = "purple heart" },
  { char = "🤎", name = "brown heart" },
  { char = "🖤", name = "black heart" },
  { char = "🤍", name = "white heart" },
  { char = "💯", name = "hundred points" },
  { char = "💢", name = "anger symbol" },
  { char = "💥", name = "collision" },
  { char = "💫", name = "dizzy" },
  { char = "💦", name = "sweat droplets" },
  { char = "💨", name = "dashing away" },
  { char = "🕳️", name = "hole" },
  { char = "💣", name = "bomb" },
  { char = "💬", name = "speech balloon" },
  { char = "👁️‍🗨️", name = "eye in speech bubble" },
  { char = "🗨️", name = "left speech bubble" },
  { char = "🗯️", name = "right anger bubble" },
  { char = "💭", name = "thought balloon" },
  { char = "💤", name = "zzz" },
}

return M
