local M = {}

M.emojis = {
  -- Smileys & Emotion
  { char = "😀", name = "grinning face" },
  { char = "😃", name = "grinning face with big eyes" },
  { char = "😄", name = "grinning face with smiling eyes" },
  { char = "😁", name = "beaming face with smiling eyes" },
  { char = "😆", name = "grinning squinting face" },
  { char = "😅", name = "grinning face with sweat" },
  { char = "🤣", name = "rolling on the floor laughing" },
  { char = "😂", name = "face with tears of joy" },
  { char = "🥰", name = "smiling face with hearts" },
  { char = "😍", name = "smiling face with heart-eyes" },
  { char = "🤩", name = "star-struck" },
  { char = "😘", name = "face blowing a kiss" },
  { char = "😋", name = "face savoring food" },
  { char = "😛", name = "face with tongue" },
  { char = "😜", name = "winking face with tongue" },
  { char = "🤪", name = "zany face" },
  { char = "🤔", name = "thinking face" },
  { char = "🤨", name = "face with raised eyebrow" },
  { char = "😐", name = "neutral face" },
  { char = "😑", name = "expressionless face" },
  { char = "😶", name = "face without mouth" },
  { char = "😏", name = "smirking face" },
  { char = "😒", name = "unamused face" },
  { char = "🙄", name = "face with rolling eyes" },
  { char = "😬", name = "grimacing face" },
  { char = "🤥", name = "lying face" },
  { char = "😌", name = "relieved face" },
  { char = "😔", name = "pensive face" },
  { char = "😪", name = "sleepy face" },
  { char = "🤤", name = "drooling face" },
  { char = "😴", name = "sleeping face" },
  { char = "🥵", name = "hot face" },
  { char = "🥶", name = "cold face" },
  { char = "🥴", name = "woozy face" },
  { char = "😵", name = "dizzy face" },
  { char = "🤯", name = "exploding head" },
  { char = "🥳", name = "partying face" },
  { char = "😎", name = "smiling face with sunglasses" },
  { char = "🤓", name = "nerd face" },
  { char = "🧐", name = "face with monocle" },
  { char = "☹️", name = "frowning face" },
  { char = "😭", name = "loudly crying face" },
  { char = "😱", name = "face screaming in fear" },
  { char = "💩", name = "pile of poo" },
  { char = "🤡", name = "clown face" },
  { char = "👻", name = "ghost" },
  { char = "👽", name = "alien" },
  { char = "🤖", name = "robot" },

  -- Gestures & People
  { char = "👋", name = "waving hand" },
  { char = "🤚", name = "raised back of hand" },
  { char = "🖐️", name = "hand with fingers splayed" },
  { char = "✋", name = "raised hand" },
  { char = "🖖", name = "vulcan salute" },
  { char = "👌", name = "ok hand" },
  { char = "🤌", name = "pinched fingers" },
  { char = "🤏", name = "pinching hand" },
  { char = "✌️", name = "victory hand" },
  { char = "🤞", name = "crossed fingers" },
  { char = "🤟", name = "love-you gesture" },
  { char = "🤘", name = "sign of the horns" },
  { char = "🤙", name = "call me hand" },
  { char = "👈", name = "backhand index pointing left" },
  { char = "👉", name = "backhand index pointing right" },
  { char = "👆", name = "backhand index pointing up" },
  { char = "👇", name = "backhand index pointing down" },
  { char = "👍", name = "thumbs up" },
  { char = "👎", name = "thumbs down" },
  { char = "✊", name = "raised fist" },
  { char = "👊", name = "oncoming fist" },
  { char = "🤛", name = "left-facing fist" },
  { char = "🤜", name = "right-facing fist" },
  { char = "👏", name = "clapping hands" },
  { char = "🙌", name = "raising hands" },
  { char = "👐", name = "open hands" },
  { char = "🤲", name = "palms up together" },
  { char = "🤝", name = "handshake" },
  { char = "🙏", name = "folded hands" },
  { char = "💪", name = "flexed biceps" },

  -- Git Commit Types (Standard & Convention)
  { char = "✨", name = "feat: new feature" },
  { char = "🐛", name = "fix: bug fix" },
  { char = "📝", name = "docs: documentation" },
  { char = "🚀", name = "deploy: deployment" },
  { char = "♻️", name = "refactor: refactoring" },
  { char = "⚡", name = "perf: performance" },
  { char = "🧪", name = "test: testing" },
  { char = "🔧", name = "chore: configuration" },
  { char = "🎨", name = "style: format/ui" },
  { char = "💄", name = "style: ui/css" },
  { char = "🔒", name = "security: security fix" },
  { char = "🚧", name = "wip: work in progress" },
  { char = "💥", name = "breaking: breaking change" },
  { char = "📦", name = "build: dependencies/packaging" },
  { char = "👷", name = "ci: continuous integration" },
  { char = "🍱", name = "assets: asset files" },
  { char = "➕", name = "add: add dependency" },
  { char = "➖", name = "remove: remove dependency" },

  -- Nature & Objects
  { char = "🌿", name = "herb" },
  { char = "🔥", name = "fire" },
  { char = "🌈", name = "rainbow" },
  { char = "☀️", name = "sun" },
  { char = "🌙", name = "moon" },
  { char = "⭐", name = "star" },
  { char = "📎", name = "paperclip" },
  { char = "🔑", name = "key" },
  { char = "💡", name = "light bulb" },
  { char = "💻", name = "laptop" },
  { char = "📱", name = "mobile phone" },
  { char = "📷", name = "camera" },
  { char = "🛠️", name = "hammer and wrench" },
  { char = "⚙️", name = "gear" },
  { char = "📌", name = "pushpin" },
  { char = "📅", name = "calendar" },

  -- Symbols
  { char = "✅", name = "check mark button" },
  { char = "❌", name = "cross mark" },
  { char = "⚠️", name = "warning" },
  { char = "ℹ️", name = "information" },
  { char = "🔴", name = "red circle" },
  { char = "🟢", name = "green circle" },
  { char = "🔵", name = "blue circle" },
  { char = "⚪", name = "white circle" },
  { char = "⚫", name = "black circle" },
  { char = "❤️", name = "red heart" },
  { char = "💙", name = "blue heart" },
  { char = "💚", name = "green heart" },
}

return M
